### ISSUE TITLE
Add .meteor/local to ignore

### ISSUE THREAD

**Issue by jackboberg** [onmodulus/modulus-cli#101]
If we update `lib/controllers/.modulus-base-ignore` to exclude this directory, uploads are a **lot** smaller and the content will be recreated as needed.

**Comment by jackboberg** [comment]
Let's prioritize getting this closed, as it may help resolve some of the recent `ENOSPC` errors.

**Comment by harlanj** [comment]
https://github.com/onmodulus/modulus-cli/blob/master/lib/controllers/.modulus-base-ignore#L4
