### ISSUE TITLE
Cannot find module when deploying Meteor 1.3

### ISSUE THREAD

**Issue by twastvedt** [onmodulus/modulus-cli#105]
Hi. I just installed modulus@next, which makes it farther than the stable version did, but it's failing here:

```
Installing a Meteor distribution in your home directory.
######################################################################## 100.0%
client/pages/admin/Admin.ts (1, 27): Cannot find module 'angular2/core'.
client/pages/admin/Admin.ts (2, 29): Cannot find module 'angular2-meteor-accounts-ui'.
```

Many more similar lines follow. It appears that it's failing to find any modules in `node_modules`. Maybe there isn't anything in `node_modules`? I'm not sure how to tell. I tried running `meteor npm rebuild`. The project runs just fine locally. I'm using Meteor 1.3, Typescript, and angular2-meteor, if that's important. Thanks!

**Comment by jackboberg** [comment]
@twastvedt Can you open a support ticket so an engineer can look into your project with you?

https://help.modulus.io
help@modulus.io

**Comment by twastvedt** [comment]
Just did. Thanks!
