### ISSUE TITLE
No more --meteor-debug?

### ISSUE THREAD

**Issue by twastvedt** [onmodulus/modulus-cli#106]
As far as I can tell, the `--meteor-debug` option is no longer available on modulus@next. Because of [this issue](https://github.com/angular/angular/issues/6380) with Angular 2, using `--meteor-debug` has been the only way I've been able to get my app to work on Modulus. Is the option still there and I'm just missing something? Thanks.

**Comment by jackboberg** [comment]
This feature was removed, or more accurately left out of the new image. We should work to get that option added back. There is a `TODO` in the new build source [here](https://github.com/onmodulus/docker-build-meteor/blob/master/bin/build#L23)

**Comment by twastvedt** [comment]
Ok. Good to know. Looking forward to it. Thanks!

**Comment by harlanj** [comment]
Closed via #139
