### ISSUE TITLE
Cannot deploy meteor application - Conversion failed

### ISSUE THREAD

**Issue by IamCharlesHan** [onmodulus/modulus-cli#107]
Updated modulus to 6.0.0 due to #66. I was able to successfully deploy once and this started to happen. 
```
Uploading project...
Upload progress [===================] 100%
Deploying project into Meteor runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Demeteorizing application...
mop, this is your first time using Meteor!
Installing a Meteor distribution in your home directory.
######################################################################## 100.0%

/mnt/home/.meteor/packages/meteor-tool/.1.3.0_3.p3s7qv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: ENOSPC, mkdir '/mnt/tmp/.tmpl0uhx2/less-2.5.6/plugin.compileLessBatch.os/npm/node_modules/meteor/babel-runtime/node_modules/regenerator/node_modules/commoner/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map/example'
Conversion failed.
```

**Comment by robandrose** [comment]
Very same problem here, after several retries it gives up and reverts to older version. Started happening today afternoon.

**Comment by IamCharlesHan** [comment]
Update: it was able to deploy successfully after 3 retries.

**Comment by harlanj** [comment]
Hey @IamCharlesHan even though you are able to deploy can you submit a ticket with Modulus Support so we can look further into this? This isn't an issue with the CLI. We can get you taken care of in support though.

**Comment by IamCharlesHan** [comment]
nvm I missed this part: ```Build failed, reverting project.```
Can you re-open this issue? It's really annoying to find out that it doesn't work after 20 minutes of "retries".

**Comment by fabyeah** [comment]
I have the same problem.

**Comment by harlanj** [comment]
@IamCharlesHan sorry for the ongoing problems. This issue is more directly related to the actual meteor build image. I created an issue for you on our [Meteor Build Image](https://github.com/onmodulus/docker-build-meteor/issues/13). We're working on improving the build process as it still is in beta. If you continue to have other issues please let us know so we can sort out the kinks

**Comment by lytstephen** [comment]
Hi, I'm having the same issue just now when deploying. Already upgraded to 1.3.2, was having that problem in 1.3.1, stopped having the problem for a little bit, and now it's back.

Please let me know if there's any help you could provide. Thanks!

**Comment by jstxx** [comment]
Try doing a meteor update, worked for me.

**Comment by fabyeah** [comment]
Update from 1.3.1 to 1.3.2.4 worked for me, too. 
Now I get an error in the build log though, about missing npm modules. I guess only users who use npm packages get this. As a workaround, I have to manually zip the source folder and upload it for deployment.

**Comment by nickpolet** [comment]
I'll try updating to meteor 1.3.2.x and see if that works. 

@fabyeah are you deploying with 'modulus deploy --include-modules'? That should send the node_modules folder up to the build server. Make sure you run npm install on your dev machine first though.

**Comment by fabyeah** [comment]
@nickpolet Thanks so much, didn't know about that. Seems to work just fine! This should be in the docs.

**Comment by erkkimon** [comment]
I had a Meteor 1.2.X project, and too old version caused an explosion. I upgraded the project to 1.3.X, and the problem was gone.
