### ISSUE TITLE
[Meteor 1.3.2.2] Deployment fails with ENOSPC

### ISSUE THREAD

**Issue by csillag** [onmodulus/modulus-cli#111]
I get this during deployment:

```
/mnt/home/.meteor/packages/meteor-tool/.1.3.2_2.5gj5bs++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: ENOSPC, mkdir '/mnt/home/.meteor/packages/flemay_less-autoprefixer/.build281303..1.2.0.1amm834++os+web.browser+web.cordova/plugin.compileLessAddAutoprefixer.os/npm/node_modules/meteor/babel-compiler/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/modules/lib'
Conversion failed.
Build attempt failed, attempting again.
```

Do you have any idea what's wrong?

**Comment by jackboberg** [comment]
Looking into it now. During build we should be providing you up to 2GB of space. Doubtful you are filling that...

**Comment by nickpolet** [comment]
I am getting this error as well.

```
Installing a Meteor distribution in your home directory.
######################################################################## 100.0%

/mnt/home/.meteor/packages/meteor-tool/.1.3.1.1ir19ok++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: ENOSPC, open '/mnt/output/.build815060.bundle/programs/.build911580.server/npm/node_modules/juice/node_modules/cheerio/node_modules/lodash/internal/baseDelay.js'
Conversion failed.
Build attempt failed, attempting again.
```

Very similar to the issue @csillag is having. I am certain that I am not using up 2GB of space during the build process on the servo. Is there anything that can be done to prevent this from happening or do we wait until a fix is found? It makes deploying impossible.

**Comment by timmakken** [comment]
I currently have a sort of similar problem but cant find a solution anywhere.

`cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/lodash/toPairs.js’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/lodash/_baseFunctions.js’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/lodash/_realNames.js’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/lodash/snakeCase.js’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/lodash/templateSettings.js’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/lodash/_cloneRegExp.js’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/lodash/_root.js’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/lodash/fromPairs.js’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/lodash/_createRange.js’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/lodash/findLast.js’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/lodash/unionWith.js’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/lodash/unzipWith.js’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/lodash/at.js’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/lodash/_hashDelete.js’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/lodash/_baseGetAllKeys.js’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/lodash/rearg.js’: No space left on device
cp: cannot create directory ‘/mnt/output/./node_modules/babel-helper-regex/node_modules/babel-runtime’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/.npmignore’: No space left on device
cp: cannot create regular file ‘/mnt/output/./node_modules/babel-helper-regex/README.md’: No space left on device
cp: cannot create directory ‘/mnt/output/./node_modules/babel-helper-regex/lib’: No space left on device
cp: cannot create directory ‘/mnt/output/./node_modules/meteor-promise’: No space left on device
cp: cannot create directory ‘/mnt/output/./node_modules/buffer-shims’: No space left on device
cp: cannot create directory ‘/mnt/output/./node_modules/meteor-babel’: No space left on device
cp: cannot create directory ‘/mnt/output/./node_modules/globals’: No space left on device
cp: cannot create directory ‘/mnt/output/./node_modules/repeat-string’: No space left on device
cp: cannot create directory ‘/mnt/output/./node_modules/mime-db’: No space left on device
cp: cannot create directory ‘/mnt/output/./node_modules/get-stdin’: No space left on device
cp: cannot create directory ‘/mnt/output/./node_modules/path-is-absolute’: No space left on device
cp: cannot create directory ‘/mnt/output/./node_modules/minimist’: No space left on device
cp: cannot create directory ‘/mnt/output/./node_modules/slash’: No space left on device
cp: cannot create directory ‘/mnt/output/./node_modules/babel-helper-get-function-arity’: No space left on device
cp: cannot create directory ‘/mnt/output/./node_modules/base64-url’: No space left on device
cp: cannot create directory ‘/mnt/output/./node_modules/meteor-ecmascript-runtime’: No space left on device
cp: cannot create directory ‘/mnt/output/./node_modules/double-ended-queue’: No space left on device
cp: cannot create directory ‘/mnt/output/./server’: No space left on device
cp: cannot create regular file ‘/mnt/output/./star.json’: No space left on device
cp: cannot create regular file ‘/mnt/output/./README’: No space left on device
Build attempt failed, attempting again.
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Package found: /package.json
Installing node 0.10.41
Installing npm 3.9.2
Build failed, reverting project.
Build attempt failed, attempting again.
`
I hope some of you guys can help. im running modulus 5.1

**Comment by dhorner** [comment]
I am getting the same thing and cannot deploy my app.  Was this issue resolved?  I do not see a fix or workaround.  I cannot deploy my app.  Any advice would be much appreciated.

`/mnt/home/.meteor/packages/meteor-tool/.1.3.3.ghwn9e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
Error: ENOSPC, open '/mnt/home/.meteor/packages/coffeescript/.build757916..1.1.0.1cr5f64++os+web.browser+web.cordova/plugin.compileCoffeescript.os/packages/.builder-tmp-file.993205'
Conversion failed.
`

**Comment by aramk** [comment]
Any update on this?

**Comment by nickpolet** [comment]
@aramk Are you still seeing this error? Did you try what @dhorner suggested? This issue was something that was very prevalent a couple of months ago, but I think was fixed with a newer build image. Have you tried contacting modulus support through their ticket system?

**Comment by aramk** [comment]
@nickpolet Yep, contacted support with this:

```
Compressing project...
17.6 MB written
Uploading project...

Deploying project into Meteor runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Now using node v0.10.41 (npm v3.8.6)
Initializing Meteor environment.
Using Meteor 1.3.2.4.
Demeteorizing application...

/mnt/home/.meteor/packages/meteor-tool/.1.3.3.4iursu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
Error: ENOSPC, open '/mnt/home/.meteor/packages/babel-compiler/.build771657..6.8.0.c97bre++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-register/node_modules/core-js/library/fn/dict.js'
Conversion failed.
Build attempt failed, attempting again.
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Now using node v0.10.41 (npm v3.8.6)
Initializing Meteor environment.
Using Meteor 1.3.2.4.
Demeteorizing application...
```
Goes like this in loops...

**Comment by harlanj** [comment]
Anyone here have some sample code Modulus can test our build servers with? We have been seeing some incidents where some projects are just too big to build on our build servers. It's really unfortunate, but we want to try everything we can to ensure that the `demeteorizer` process stays on the build servers. It seems like many of the issues are with `Meteor@1.3.2`.

**Comment by jackboberg** [comment]
This does not seem to be a CLI issue, so I would like to move this discussion to [the build repo](https://github.com/onmodulus/docker-build-meteor/issues/29) where we can address the solution more directly.
