### ISSUE TITLE
Modulus deploy encountering <error uploading> at upload progress 50%-60%

### ISSUE THREAD

**Issue by darrenwng** [onmodulus/modulus-cli#112]
My compressed file is only 12.4 MB. 

Am using 
modulus-cli@5.0.1
meteor@1.2.1

Environment configuration on modulus is for NodeJS environment. 
I have noticed that there is a new Meteor environment configuration which was not there previously. 

Usually modulus deploy take a couple of minutes to deploy. Now the time taken to upload has increased significantly. Is the timeout configuration still at 5 minutes?

**Comment by jackboberg** [comment]
Yes, the upload timeout is 5 minutes. When did the time to upload increase for you? Have you had successful deploys of this code base within the last month?

The new Meteor image has helped resolve a lot of issues some users were having with long/failed deploys. You could try creating a new project using that project type and seeing if it resolves this for you. Be sure to use the 'beta' CLI tool when deploying to the new image type:

`npm i modulus@next -g`

**Comment by darrenwng** [comment]
Hi Jack,
Thanks for getting back to me.
Yes. my codes have been working fine for the past 2 months. For this deployment, I just wanted to make some changes to the text values. 
npm i modulus@next -g

I tried doing this but my codes are currently on meteor 1.2.1During modulus deploy it uses meteor 1.3.2.4 to demeteorize and it hangs during conversion. 
There needs to be quite a number of changes required to migrate to the meteor 1.3 and we are not ready to move yet. 
RegardsDarren

**Comment by jackboberg** [comment]
Sorry for not mentioning that, yes the new Meteor image requires `>= 1.3.x`. If you have been able to deploy successfully recently, we haven't shipped any changes to the Node image or API that should affect this. Can you open a support ticket so an engineer can dig in to your specific issues.

`help [at] modulus.io`
