### ISSUE TITLE
Error on modulus deploy a meteor app in nodejs runtime

### ISSUE THREAD

**Issue by judsonbsilva** [onmodulus/modulus-cli#113]
Meteor -v 1.2.1
Modulus -v 6.0.0
Node -v 0.12.13
Npm -v 2.15.0
Demeteorizer -v 3.1.0

When run the command

`demeteorizer`
`modulus deploy .demeteorized`

console shows

Compressing project...
4.7 MB written
Uploading project...
Upload progress [===================] 100%
Deploying project into Node.js runtime...

[Error] There was a problem deploying your project.

**Comment by harlanj** [comment]
@judsonbsilva this isn't a problem with the CLI. We were having issues with our build hosts. These issues are now resolved. If you continue to have issues deploying (more specifically seeing that error above) please submit a ticket to our support team.
