### ISSUE TITLE
[Meteor 1.3.2.4] [Modulus 6.0.0] ERROR: No main or start script found. There is no application to run.

### ISSUE THREAD

**Issue by victorlambert** [onmodulus/modulus-cli#115]
Hi guys, 

I'm trying the new modulus cli and meteor runtime.
Deployment is running fine but I get this error when starting the app (from the logs) : 

```
Now using node v0.10.41
Found package.json: ./.modulus/nvm/package.json
WARNING: Main file not specified in package.json.
WARNING: Looking for common main file names: index.js, app.js, server.js, main.js.
ERROR: No main or start script found. There is no application to run.
```

I do have a start script in my package.json : 
```
...
  "scripts": {
    "start": "meteor --settings settings-development.json",
...
```
Any idea ?
Thanks for the great work

**EDIT :** 
After downgrading to 5.0.1 and 5.0.0 I get the same error ... everything was working fine before I tried the new cli/runtime. Need to deploy today, hope I will find the issue.

**Comment by HynesIP** [comment]
+1

The CLI script found package.json in my in my /tests folder, and in an old package folder, which had previously been ignored.

Getting this happy error:

Now using system version of node: v0.10.38.
WARNING: No package.json file found.
WARNING: Main file not specified in package.json.
WARNING: Looking for common main file names: index.js, app.js, server.js, main.js.
ERROR: No main or start script found. There is no application to run.

And, "Unable to connect to any application instances." app response.

**Comment by harlanj** [comment]
Hey guys sorry for the issues. As for now, you will need to use the cli tool versions `next`, `v6.0.0` or `latest` to deploy your Meteor app into the Meteor runtime. This isn't the right repo for this issue. I'll move it for you. Our build/run images all have their own repos for issues. The link to the issue on this is [here](https://github.com/onmodulus/docker-run-meteor/issues/9).
