### ISSUE TITLE
Meteor 1.2.1 deploy failed

### ISSUE THREAD

**Issue by raduchiriac** [onmodulus/modulus-cli#116]
Just noticed after updating to v6.0.0, the CLI will not recognise my project. No more `Meteor project detected...` and while the compressed project will be successfully uploaded, modulus logs will just throw:
```
WARNING: No package.json file found.
WARNING: Main file not specified in package.json.
WARNING: Looking for common main file names: index.js, app.js, server.js, main.js.
```

Is METEOR@1.2.1 obsolete?

EDIT: Normally my compressed meteor project is ~30Mb, while with 6.0.0 it's only 4Mb.

**Comment by jbrozena22** [comment]
I had the same problem but in Meteor 1.3. The CLI tool never recognized it was a Meteor package (like it does in 5.0.1) so it never went through and packaged it as Meteor requires. Instead all of the files were just uploaded directly.

**Comment by harlanj** [comment]
We now have an official Meteor runtime. The breaking change in the `v6.0.0` is that the `demeteorizer` step is now done on the build hosts. But it's only done for Meteor images. If you want to continue to have your project `demeteorized` locally you need to downgrade your version of the CLI to anything below `v6.x`. If you have a Meteor project and need to have your project `demeteorized` locally, this is the way to go. If you want to use the new Meteor runtime, you need to update your project's runtime to Meteor and then deploy using the latest version of the CLI. Sorry for the confusion. You can read our [blog post](http://blog.modulus.io/the-new-meteor-build-image) on how the Meteor runtime works. Also, the new Meteor runtime only works with `meteor@1.3.x`. So if you want to keep your app running an older version of Meteor you will need to keep your project as a Node.js project and deploy using an older version of the CLI. Anything under `v6.x`. Sorry for the confusion. Let me know if this clears up anything.

**Comment by raduchiriac** [comment]
Oh it's my bad, I didn't follow the news.
That is good to know, I think I will stay with 5.0.1 for a while. 

Thanks for the info.
