### ISSUE TITLE
Deploy meteor 1.2 app crashes

### ISSUE THREAD

**Issue by bitomule** [onmodulus/modulus-cli#119]
I'm trying to deploy an old meteor app with just one fix but meteor cli crashes with:

```
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Now using node v0.10.41 (npm v3.8.6)
Initializing Meteor environment.
Using Meteor 1.3.2.4.
Demeteorizing application...
--server-only: unknown option.
Usage: meteor build <output path> [--debug] [--directory]
          [--mobile-settings settings.json] [--server http://example.com:3000]
```

Any idea? How can I deploy using an older version? If I update my project to 1.3 I get tons of errors related to Stripe, Moment and 3rd party libraries.

**Comment by fiveisprime** [comment]
For Meteor 1.2, you'll need to use the Node.js project runtime and modulus cli version 5.0.1.

From your meteor application's directory run

```sh
$ npm install -g modulus@5.0.1
$ modulus project create -r node.js -s 512
$ modulus deploy
```

Once you have verified that is working, t's safe to delete your old project.

**Comment by bitomule** [comment]
Thanks! Worked without issues.
