### ISSUE TITLE
Github linked account login error

### ISSUE THREAD

**Issue by lytstephen** [onmodulus/modulus-cli#122]
```
[?] Enter your GitHub username or email: xxxxxxxx
[?] Enter your password:
[Error] GitHub account not found. Please link your account with GitHub using the web portal to use GitHub authentication.
```

I cannot login to my modulus account both with the CLI, nor the web portal login. I cannot deploy or do anything with my github-linked account. Please assist as soon as possible. Thank you

**Comment by harlanj** [comment]
@lytstephen Sorry for the trouble and getting back to you so late. Hopefully, this is resolved by now. If not, I can assist. When Modulus links your GitHub account to your Modulus account, we store the email address associated. So this way you can still submit a `Password Forgot` request. Can you do this please? 

Once you complete this, then unlink your GitHub account, then relink it. You will not lose anything associated with your account. This will just re-establish the link between your GitHub and Modulus account.

**Comment by lytstephen** [comment]
@harlanj Fortunately I had a colleague who was already logged in and set a username/pw for me. Thanks for the info though, hope it'll help others who are in same situation
