### ISSUE TITLE
deploy - Cordova error: Plugin "es6-promise-plugin" not found

### ISSUE THREAD

**Issue by Wade-BuildOtto** [onmodulus/modulus-cli#124]
I found that it builds when I run the deploy command a second time, odd that it just doesn't ignore it, as it was trying to remove it anyways. I would prefer to not have to do it twice.

Errors executing Cordova commands:         
                                              
   While removing plugins                     
   com.googlemaps.ios,com.pylonproducts.wifiwizard,cordova-plugin-compat,cordova-plugin-device,cordova-plugin-geofence,cordova-plugin-geolocation,cordova-plugin-googlemaps,cordova-plugin-meteor-webapp,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-whitelist,cordova-plugin-wkwebview-engine,es6-promise-plugin
   from Cordova project:
   Cordova error: Plugin "es6-promise-plugin" not found. Already uninstalled?
   (If the error message contains suggestions for a fix, note that this may not apply to the Meteor integration. You can try running again with the --verbose option to
   help diagnose the issue.)
undefined                                     
[Error] Error: Conversion failed.

**Comment by harlanj** [comment]
Hey @Wade-BuildOtto. We apologize for the late response. This problem is currently under the wrong repo. I'll move your issue to the [`docker-build-meteor`](https://github.com/onmodulus/docker-build-meteor/issues/23) repo. You can check out your issue and any further comments there.
