### ISSUE TITLE
[Error] There was an error uploading.

### ISSUE THREAD

**Issue by ashconnell** [onmodulus/modulus-cli#126]
Just signed up with the intention of moving all of my projects to modulus, but the first project i tried to deploy fails:

```
Compressing project...
67.4 MB written
Uploading project...
Upload progress [===                ] 21%{}

[Error] There was an error uploading.
```

My upload speed here is slow and I saw mentions of a 5 minute timeout - is this accurate? 

If this is the case, the CLI could report a timeout (instead of an error) and offer another solution for me to continue (of which i have no idea)

**Comment by ashconnell** [comment]
I resolved this by trimming my bundle down to 7mb with a .modulusignore file :)

**Comment by harlanj** [comment]
Hey @ashconnell! Sorry for the trouble. When this happens, it's normally not a problem with the CLI. It's best to contact Modulus support in this case. Sorry for the late response as well. If the issue happens again, please don't hesitate to reach out to our support team!
