### ISSUE TITLE
Meteor 1.4 deploy with modulus

### ISSUE THREAD

**Issue by chaoslion** [onmodulus/modulus-cli#137]
Hello

version of node.js at the build is  "v0.10.41 (npm v3.9.6)"

Meteor 1.4 needs node.js 4.4.7

is it a way to fix it with modulus.

Best Regards

**Comment by jackboberg** [comment]
Here are open issues where we are attempting to resolve this:

onmodulus/demeteorizer#191
onmodulus/docker-build-meteor#25
