### ISSUE TITLE
just upgraded to Mac OS Sierra - cli not working. 

### ISSUE THREAD

**Issue by mvgalle** [onmodulus/modulus-cli#138]
"modulus: command not found"
- Not sure if this is a compatibility problem with Mac OS Sierra and the Modulus-cli. I did try to reinstall modulus cli, but i'm still getting "command not found".

**Comment by franvarney** [comment]
This sounds like a path issue. In your terminal can you type `which node` and see if the path that is output is part of the PATH variable (you can type `echo $PATH` to see this). You can also try `which modulus` to see if that path is set correctly.

 So, for example, if `which node` shows `/usr/local/bin/node`, then `/usr/local/bin` needs to be included in `PATH`.

**Comment by jackboberg** [comment]
You might try `npm bin --global`, that is the path where npm _should_ be putting the module if you run `npm i modulus -g`

**Comment by mvgalle** [comment]
Thank you @jackboberg and @franvarney for the advice. For some reason my update to Sierra seems to have messed up all my paths and rather than spend hours trying to untangle everything, I went ahead and completely uninstalled Node. I then installed NVM [https://github.com/creationix/nvm/blob/master/README.markdown](url)

And then added installed the Modulus CLI again. 

All is working GREAT again.
