### ISSUE TITLE
modulus deploy with --node-version flag results in error

### ISSUE THREAD

**Issue by timmakken** [onmodulus/modulus-cli#149]
Using modulus CLI 6.3 and meteor 1.4.1.1 running on a modulus Meteor runtime.
i get this error when i define a node version flag:
`  error: unknown option `--node-version'
`
So i assume theres something wrong but i cant seem to fix it.

Edit:

Ive also added the required package.json params but still not able to deploy 

and when deployed without the node version flag i get this error:
`[Error] There was a problem deploying your project.`

**Comment by jackboberg** [comment]
Can you share the output from:

```
› modulus deploy -h
project deploy (deploy) [options] <directory>
Deploys a directory's contents to the selected project.
The current working directory is used if no directory is specified.
By default a project type will be detected and any additional actions required will be taken.
  options:
    -p, --project-name      Name of the project to deploy. Prompts are skipped when specified.
    -m, --include-modules   Flag that indicates whether or not to include the node_modules folder in the bundle.
    -r, --registry          Specify a registry to install modules from.
    -w, --with-tests        Specifies that tests should be run before deploying this project.
        --node-version       Specified version of node to use when running application.
        --npm-version        Specified version of npm to use when building application.
    -d, --debug             Specifies to pass the debug flag to demeteorizer.
```

You should see `--node-version` in the list of available options..

**Comment by timmakken** [comment]
My result on modulus deploy -h
`project deploy (deploy) [options] <directory>
Deploys a directory's contents to the selected project.
The current working directory is used if no directory is specified.
By default a project type will be detected and any additional actions required will be taken.
  options:
    -p, --project-name      Name of the project to deploy. Prompts are skipped when specified.
    -m, --include-modules   Flag that indicates whether or not to include the node_modules folder in the bundle.
    -r, --registry          Specify a registry to install modules from.
    -w, --with-tests        Specifies that tests should be run before deploying this project.
    -D, --meteor-debug      Override debug mode for meteor project.
`

Im thinking its using an older version , but that wierd because the latest version is definetly installed

Is there something like modulus --version or something i can use to double check if its using the latest?

**Comment by jackboberg** [comment]
You guessed it:

```
› modulus --version
6.3.1
```

If you are not getting that, try comparing:

```
› which modulus
/usr/local/var/nvm/versions/node/v4.5.0/bin/modulus

› npm bin --global
/usr/local/var/nvm/versions/node/v4.5.0/bin
```

If they don't match, it means you have a version of `modulus` that is not the version you installed globally..

**Comment by timmakken** [comment]
Mine keeps hanging on 4.x.x , i think the problem lies with npm

**Comment by jackboberg** [comment]
I don't quite understand what you mean by "hanging on 4.x.x". Do you mean your project won't deploy when using node `v4.x`? If so, Modulus supports running/deploying your app using `0.10.x`. Just set an `engines` property in your `package.json` and we will honor it.

**Comment by timmakken** [comment]
my modulus version was stuck and didnt apply the update to 6.3.0 , even after readding it to npm.
turned out there was an issue with my npm, had to reinstall npm completely to fix the issue.

the version i was running was still on 4.x.x even after updating.
This issue can be removed as there was something wrong with npm and not with modulus.
