### ISSUE TITLE
conflict while deploying Meteor project  with new version of modulus

### ISSUE THREAD

**Issue by aliyekurumlu** [onmodulus/modulus-cli#150]
I have a meteor project  (running on version1.2.1) and i have upgraded the modulus from 5.0.1 to 6.3.1. 
I can not deploy my project anymore. 
If I switch to Meteor Runtime as suggested. But then I got  problem with the version of Meteor. 
Is there a way to go back to older version of Modulus (5.0.1)?

**Comment by jackboberg** [comment]
`npm install modulus@5.0.1 --global`

The `6.x` release requires Meteor > `1.3` and uses the Meteor runtime. When you are ready to upgrade, try doing so in a new project and then you can migrate your production app..
