### ISSUE TITLE
Foreground color not visible in common terminal themes (solarized)

### ISSUE THREAD

**Issue by davidpelaez** [onmodulus/modulus-cli#16]
![screen shot 2014-08-19 at 7 48 28 pm](https://cloud.githubusercontent.com/assets/313232/3975222/bbb999da-2803-11e4-81f1-6d2a9c5f3c69.png)

The screenshot is pretty self explanatory and this problem is very rare in most CLI apps.

**Comment by harlanj** [comment]
Since this is relevant to the issue listed above, shouldn't this be closed and resolved in the theme's issue?
