### ISSUE TITLE
Project deletion should be possible

### ISSUE THREAD

**Issue by davidpelaez** [onmodulus/modulus-cli#18]
I couldn't find a way to delete a project, this should be possible.

**Comment by pandeysoni** [comment]
In project, select one project, in left tab menu, there is administrator, click on administrator, on administrator page, you will get the option to delete project.

**Comment by pushred** [comment]
It should be possible to do this programmatically though and it isn't. In my case we create many temporary projects used for deploying a build for review, similar to Heroku's [Pull Request apps][1]. We stop these projects after the PRs are closed but it'd be great to be able to delete them as well as part of that cleanup.

[1]: https://devcenter.heroku.com/articles/github-integration-pull-request-apps

**Comment by harlanj** [comment]
Just published a new version of the CLI. New version is 3.8.0.
