### ISSUE TITLE
Expand the support for tokens to env and other actions

### ISSUE THREAD

**Issue by LarsBuur** [onmodulus/modulus-cli#23]
I would very much like to be able to update my environment settings from my build server using the modulus cli. TOKENS seems only supported in the deploy action.

What I would like to do is something like this.

export MODULUS_TOKEN=xxx 
modulus env set "tada" "todo"

without the modulus cli asking me about the project name and just rely on the token set.

**Comment by tzmanics** [comment]
hi @LarsBuur sorry for the big delay! so just to catch up, currently you are still asked to choose the project when setting  your environment variables. if this is still an issue for you please re-open this issue and we'll look into it. thank you!
