### ISSUE TITLE
Specify default project

### ISSUE THREAD

**Issue by rowanmanning** [onmodulus/modulus-cli#3]
Hi, one of the very few irritations I've been having with the command line tool is that you have to select a project every time you deploy (please correct me if I'm wrong).

Would it be possible to allow a `.modulus` file or something inside a directory which specifies the project to deploy to? That way I can just run `modulus deploy` without having to remember to wait and select a project.

It will probably also avoid potential mistakes – what if I accidentally select the wrong project?

Thanks,
Rowan

**Comment by daveyjones** [comment]
I actually really like this solution, and I think it makes a lot of sense in most situations. We deploy to our staging environment way more often than our production environment, so in our `package.json` file, we've specified the following default:
````
"mod-project-name": "app-staging"
````
This allows us to simply use `modulus deploy` to deploy to our staging environment. Then, when we're ready to deploy to our production environment, we simply use the `-p` flag:
```
modulus deploy -p app-production
```
In my opinion, having to specify the name of the production project with the `-p` flag creates just the right amount of friction.
