### ISSUE TITLE
Meteor deployment failing — can't find bcrypt

### ISSUE THREAD

**Issue by lourd** [onmodulus/modulus-cli#30]
Using modulus CLI 3.01 on OS X 10.9. The app is on Meteor 0.9.4

The error is:

```
Error: Can't find npm module 'bcrypt'. Did you forget to call 'Npm.depends' in package.js within the 'npm-bcrypt' package?
    at Object.Npm.require (/mnt/data/1/programs/server/boot.js:113:17)
    at Package (packages/npm-bcrypt/wrapper.js:1)
    at /mnt/data/1/programs/server/packages/npm-bcrypt.js:21:4
    at /mnt/data/1/programs/server/packages/npm-bcrypt.js:30:3
    at /mnt/data/1/programs/server/boot.js:168:10
    at Array.forEach (native)
    at Function._.each._.forEach (/mnt/data/1/node_modules/underscore/underscore.js:79:11)
    at /mnt/data/1/programs/server/boot.js:82:5
[2014-10-30T22:54:44.877Z] Failed to start application.
```

I've re-deployed a few times to no avail. Help!

**Comment by davidryanspeer** [comment]
Hey @lourd,
Not sure if you're still experiencing issues but here's a quick fix.

Modulus has a new technology stack for new deploys. Start off by fully stopping and starting your application. This will ensure you're on the new stack.

Next, update your command line tool with: `$ npm update -g modulus`

Currently, Meteor is not fully compatible with Node 0.12.0 on Modulus. Updating you modulus CLI will ensure Meteor deploys with the supported Node version defined when deployed.

More info [here](http://davidryanspeer.com/blog/JubhXDEyyAoDAnGSy)

Cheers,
David

**Comment by lourd** [comment]
Hey David, thanks for getting back to me. We've actually since decided to run our own infrastructure and are using Digital Ocean & Compose.io now. Modulus was great to quickly prototype on but we're happy to have our own machines now.

Best,
Louis
