### ISSUE TITLE
Static JS file unavailable in Meteor app after "modulus deploy"

### ISSUE THREAD

**Issue by swese44** [onmodulus/modulus-cli#38]
I'm upgraded a Meteor app to 1.0.2.1 and upgraded all its packages. There's a ShareJS package using the Ace editor. Everything works correctly locally.

I run '''.demeteorizer''', cd into the .demeteorized directory, then run '''modulus deploy'''. The build and deploy is successful, but the browser receives a 500 error when trying to retrieve this file:
'''packages/mizzao_sharejs/.npm/package/node_modules/share/webclient/ace.js'''

Here's the broken production website:
https://www.seemecode.com/

Here's the server log:
'''{"line":"457","file":"webapp_server.js","message":"Error serving static file Error: ENOENT, stat '/mnt/data/2/programs/web.browser/packages/mizzao_sharejs/.npm/package/node_modules/share/webclient/ace.js'","time":{"$date":1419661767968},"level":"error"}'''

Any ideas why this works locally, but not after running '''.demeteorizer''' and '''modulus deploy'''? Thanks!

**Comment by vitch** [comment]
Did you ever figure this out? I've got a similar problem with a different static file (on a project created with `. demeteorizer` but deployed to a different host (via [Dokku](https://github.com/progrium/dokku))

**Comment by vitch** [comment]
My problem is unrelated! The file just wasn't there for me because it was `.gitignore`d and didn't get pushed!
