### ISSUE TITLE
What happens when there changes to be made

### ISSUE THREAD

**Issue by christiannwamba** [onmodulus/modulus-cli#42]
I have a project I deployed to modulus using 'modulus deploy'. Later I had to changes to be made to just a file and that made me miserable because I used the same command and it overwrote the existing files and all the uploaded files that do not exist on the local server were gone. How can I make changes to the server without touching any other files?

**Comment by fiveisprime** [comment]
Unfortunately, partial deploys are not supported right now. This is a pretty
common request so expect to see something happen soon.
