### ISSUE TITLE
Deprecated method for modulus deploy with Meteor app

### ISSUE THREAD

**Issue by gwendall** [onmodulus/modulus-cli#46]
I am getting this warning when deploying my app (deployment works fine though).
``` sh
Bundling Meteor App...
This command has been deprecated in favor of 'meteor build', which allows you
to build for multiple platforms and outputs a directory instead of a single
tarball. See 'meteor help build'for more information.
```

**Comment by fiveisprime** [comment]
This is an issue with the [demeteorizer](https://github.com/onmodulus/demeteorizer/issues/97) package that we haven't fixed quite
yet.

Thanks for the report. :)
