### ISSUE TITLE
Error when ```modulus deploy``` version: 3.15.0

### ISSUE THREAD

**Issue by Chun-Yang** [onmodulus/modulus-cli#54]
I have a meteor app.
When I do modulus deploy, I get error:

TypeError: Cannot read property 'concat' of undefined
    at /Users/trent/.nvm/versions/node/v0.12.2/lib/node_modules/modulus/lib/common/verifyPackage.js:74:25
    at /Users/trent/.nvm/versions/node/v0.12.2/lib/node_modules/modulus/node_modules/async/lib/async.js:190:13
    at /Users/trent/.nvm/versions/node/v0.12.2/lib/node_modules/modulus/node_modules/async/lib/async.js:116:25
    at /Users/trent/.nvm/versions/node/v0.12.2/lib/node_modules/modulus/node_modules/async/lib/async.js:187:17
    at /Users/trent/.nvm/versions/node/v0.12.2/lib/node_modules/modulus/node_modules/async/lib/async.js:491:34
    at checkStartScript (/Users/trent/.nvm/versions/node/v0.12.2/lib/node_modules/modulus/lib/common/verifyPackage.js:11:52)
    at /Users/trent/.nvm/versions/node/v0.12.2/lib/node_modules/modulus/lib/common/verifyPackage.js:70:7
    at /Users/trent/.nvm/versions/node/v0.12.2/lib/node_modules/modulus/node_modules/async/lib/async.js:486:21
    at /Users/trent/.nvm/versions/node/v0.12.2/lib/node_modules/modulus/node_modules/async/lib/async.js:185:13
    at iterate (/Users/trent/.nvm/versions/node/v0.12.2/lib/node_modules/modulus/node_modules/async/lib/async.js:108:13)

**Comment by fiveisprime** [comment]
Update to modulus@3.15.1. (`$ npm install -g modulus`) and try again.

Sorry about that!

**Comment by Chun-Yang** [comment]
Thanks! That was QUICK!
