### ISSUE TITLE
meteor-debug broke in 5.0

### ISSUE THREAD

**Issue by mikepaszkiewicz** [onmodulus/modulus-cli#56]
Code is not being deployed minified using either -D or --meteor-debug

**Comment by mikepaszkiewicz** [comment]
@fiveisprime How do I install your fork?

**Comment by fiveisprime** [comment]
I'll just merge and publish it. :)

**Comment by fiveisprime** [comment]
Landed in modulus@5.0.1; run `$ npm install -g modulus` and you'll get it.

**Comment by mikepaszkiewicz** [comment]
Thanks
