### ISSUE TITLE
respect bundledDependencies when deploying

### ISSUE THREAD

**Issue by AdamMagaluk** [onmodulus/modulus-cli#6]
I think it would be useful if modulus would add any node module that exists in the bundledDependencies to the zip archive. A lot of my use case is working with a project that has a number of private repositories that i want bundled with my application but not necessarily all the standard node_modules like express/request....

This wouldn't be a big issue except that modulus does not follow symbolic links to folders in node_modules when the -m flag is specified. Making any 'npm link' commands people do not get zipped in the archive.

**Comment by tzmanics** [comment]
Hi @jedireza this should no longer be an issue so I'm going to close it but if you are still having problems related to this issue please feel free to re-open & add comments. Thanks!
