### ISSUE TITLE
Can't find npm module 'meteor-deque'

### ISSUE THREAD

**Issue by mohsinali1317** [onmodulus/modulus-cli#60]
I am trying to deploy my meteor app on Modulus but I am getting these errors on the console

    Error: Can't find npm module 'meteor-deque'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package?
    at Object.Npm.require (/mnt/app/bundle/programs/server/boot.js:175:17)
    at Meteor.startup (packages/meteor/fiber_helpers.js:17:1)
    at /mnt/app/bundle/programs/server/packages/meteor.js:816:4
    at /mnt/app/bundle/programs/server/packages/meteor.js:1274:3
    at /mnt/app/bundle/programs/server/boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (/mnt/app/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    at /mnt/app/bundle/programs/server/boot.js:137:5

    npm ERR! Linux 3.13.0-46-generic
    npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.40/bin/npm" "start"
    npm ERR! node v0.10.40
    npm ERR! npm  v3.3.10
    npm ERR! code ELIFECYCLE
    npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
    npm ERR! Exit status 8
    npm ERR! 
    npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node ../../main
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls meteor-dev-bundle
    npm ERR! There is likely additional logging output above.

My node version is 0.12.7
My meteor version is 1.2.1

**Comment by harlanj** [comment]
Hey @mohsinali1317 what is the version of node that Modulus is deploying your project with?

**Comment by mohsinali1317** [comment]
I am not sure but how do I check that?

**Comment by harlanj** [comment]
Node just released another version (https://nodejs.org/en/blog/release/v5.0.0/). It may have changed some dependencies. You can check on the logs page of your project. You would check the `Build Output` instead of application logs. But this isn't an issue with the cli, more so the version of node that Modulus uses for your application. If you submit a ticket you can get further assistance.

**Comment by mohsinali1317** [comment]
Okay I will submit a ticket then. Can I get a link to submit a ticket?
