### ISSUE TITLE
can't deploy rochet.chat meteor app unless using -D option

### ISSUE THREAD

**Issue by maabed** [onmodulus/modulus-cli#62]
When i try to deploy Rocket.Chat https://github.com/RocketChat/Rocket.Chat its showing this error 

```
WARNING: The output directory is under your source tree.

Compressing project...
26.9 MB written
Uploading project...
Upload progress [===================] 100%Unknown body type.
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>

Upload progress [===================] 100%
Deploying project into Node.js runtime...
Upload progress [===================] 100%
[Error] socket hang up
```

its deployed fine when using -D flag
using Modulus v 5.0.1

**Comment by harlanj** [comment]
That looks like our API was timing out and/or closing the connection on you. If you're still having issues I would recommend submitting a ticket to their support team so they can keep looking into this for you.

**Comment by orozcorp** [comment]
I also have the same problem

Compressing project...                        
64.7 MB written
Uploading project...
Upload progress [===================] 100%Unknown body type.
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>

Upload progress [===================] 100%
Deploying project into Node.js runtime...
 
[✓] SterlingPlasma running at sterlingplasma-58960.onmodulus.net

**Comment by Futurama56** [comment]
+1 on Meteor 

Compressing project...
35.5 MB written
Uploading project...
Unknown body type.
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>

**Comment by lytstephen** [comment]
I just ran into the exact same problem. Is this a temporary thing when modulus server is down or something? 

My project now just stuck on 'deploying' ... good thing the website is still running fine, but I'd like to deploy my updates ...

**Comment by harlanj** [comment]
@lytstephen @Futurama56 if this happens again can you contact support? This problem is outside of the scope of our CLI.
