### ISSUE TITLE
Avoid "output directory is under your source tree" Meteor warning

### ISSUE THREAD

**Issue by fiveisprime** [onmodulus/modulus-cli#63]
Bundle the project to a temp directory rather than the local directory before deploying.

**Comment by rub1e** [comment]
@fiveisprime hi, couple of questions:

* Are there any problems arising from this? I've just been ignoring it (...!) and haven't encountered any obvious issues
* How would you go about bundling the project to a temp directory as you suggest?

**Comment by fiveisprime** [comment]
There are no problems, it's just ugly. The solution requires some change to the CLI: rather than bundle to the default location, specify `process.env.TMPDIR` (being sure to handle the cases with Windows as well) then deploy from that location.

**Comment by rub1e** [comment]
Thanks @fiveisprime, that makes sense. (And if Modulus ever asks how speedy customer service is, I'll give you 11/10)
