### ISSUE TITLE
Meteor CLI downgraded deploy, server in reset loop

### ISSUE THREAD

**Issue by mikepaszkiewicz** [onmodulus/modulus-cli#67]
Based on #58, I had to downgrade my Modulus CLI to deploy my Meteor project. After successfully getting it running, it arbitrarily resets every ~2-5- minutes, sometimes multiple times in a row. Scratching my head, as there's no error getting thrown. Not sure if this is symptomatic of something out of date with the CLI, or if I'm just overlooking something here...

 
```
Now using node v0.10.40

Found package.json: ./package.json

Start script specified in package.json: node main.js

Running command: npm start

> habitat@0.0.1 start /mnt/app
> node main.js

```
etc...

**Comment by harlanj** [comment]
This looks be to something outside of the CLI. If you're still having this issue you can open a ticket with Modulus support.
