### ISSUE TITLE
Use .modulusignore on meteor projects

### ISSUE THREAD

**Issue by jackboberg** [onmodulus/modulus-cli#72]
See onmodulus/demeteorizer#162

I think the solution is to copy the file after running `demeteorizer`, probably [here](https://github.com/onmodulus/modulus-cli/blob/master/lib/controllers/project.js#L677)

**Comment by franvarney** [comment]
Is this still relevant?

**Comment by jackboberg** [comment]
Not with the new `meteor` images. Since we don't use `demeteorizer` on the client any more, we are no longer deploying from a created sub-directory.
