### ISSUE TITLE
Unable to set things that looks like flags as env var values

### ISSUE THREAD

**Issue by tzmanics** [onmodulus/modulus-cli#77]
If the values looks like a command line flag the command fails with an unknown option error. See screenshot.
![screen shot 2016-01-22 at 2 05 07 pm](https://cloud.githubusercontent.com/assets/3611928/12520205/2d0eee4e-c111-11e5-972a-cb931cef804d.png)

Brandon Cannaday  added a comment - 05/Feb/14 11:21 AM
Solution is to put a naked -- in front of value. 

$ modulus env set EXEC_ARGS -- "--harmony" 

I think as long as it's documented this is an acceptable solution.

**Comment by fiveisprime** [comment]
This is a normal CLI thing and totally legit. No bug here :bug: :metal:
