### ISSUE TITLE
Option to automatically navigate to project after deploy

### ISSUE THREAD

**Issue by tzmanics** [onmodulus/modulus-cli#86]
The first thing I always do after a deploy is visit the site. Would be nice have an option that just automatically opens the website after the deploy is done. 

Something like: 
`modulus deploy --navigate-on-deploy`

**Comment by tzmanics** [comment]
just fyi for all interested in this concept you could just write an alias for `modulus deploy && open https://<onmodulus url>`

**Comment by harlanj** [comment]
Matt created this feature (to open a project in the browser via cli command) a while back. I see it got rebased into my PR #73 and wanted to make not of it
