### ISSUE TITLE
New "meteor-webpack" projects built with Mantra require to run "npm install" before running the instance

### ISSUE THREAD

**Issue by tomitrescak** [onmodulus/modulus-cli#95]
Is it possible to run "npm install? before the application is run?
Can you please pinpoint me to the correct file where this should be done?

Kindly appreciated

**Comment by tzmanics** [comment]
Hi @tomitrescak we always run`npm install` before we run your application instance. Is there something coming up that makes it seem it is not or are you just making sure?

**Comment by tomitrescak** [comment]
Sorry, it looks like the meteor-webpack does not pack the package.json as part of the application as demetoriser avoids it. Mistake on their side. Thanks.
