### ISSUE TITLE
Error when deploying meteor application from CLI

### ISSUE THREAD

**Issue by aloisbarreras** [onmodulus/modulus-cli#98]
I get this error on version 5 and up of the CLI when deploying my meteor application.

```
Errors prevented bundling:                    
While linking the program:                    
error: ast:integration-configs is not compatible with architecture
'os.linux.x86_64'

undefined                                     
[Error] Error: Conversion failed.
```

Downgrading to version 4.0.2 gets rid of the issue, but I can't figure out how to fix it on recent versions.

**Comment by tzmanics** [comment]
Hey @aloisbarreras this is because compiled modules aren't being built correctly by Meteor (https://github.com/meteorhacks/npm/issues/40) BUT we are working towards solving this problem! For now though, your best bet is working with our older version.

**Comment by nick-gudumac** [comment]
I get the same error, with Meteor 1.3.2.1. Please help.

```
Executing build.
Demeteorizing application...
mop, this is your first time using Meteor!
Installing a Meteor distribution in your home directory.
######################################################################## 100.0%
Upload progress [===================] 100%
/mnt/home/.meteor/packages/meteor-tool/.1.3.2_1.18hmnqp++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
undefined
Conversion failed.
Build attempt failed, attempting again.
```

**Comment by fabyeah** [comment]
@nick-gudumac I get your error, too with Meteor 1.3 and modulus cli 6. I have to zip the source folder and upload it manually for it to work :(

**Comment by tzmanics** [comment]
Hi @nick-gudumac, @fabyeah & @aloisbarreras thanks for reaching out, sorry the build is failing for you. This issue is more directly related to the actual meteor build image. @harlanj created an issue for you on our Meteor Build Image. We're working on improving the build process as it still is in beta. If you continue to have other issues please let us know on that issue so we can sort out the kinks.
