### ISSUE TITLE
Modulus Deploy: 56mb compressed app repeatedly fails to upload around 40-50%

### ISSUE THREAD

**Issue by nabilfreeman** [onmodulus/modulus-cli#99]
I'm trying to upload a Meteor app that is approximately 120mb uncompressed, and 56mb after the zipping that happens during `modulus deploy`.

The upload constantly fails around 50%.

Here's the error:

```
Meteor project detected...
                                              
WARNING: The output directory is under your source tree.
                                              
Compressing project...                        
56.0 MB written
Uploading project...
Upload progress [========           ] 45%{}

[Error] There was an error uploading.
```

I have tried several completely separate network connections.

Is there some sort of size limit on Modulus deploys? Maybe 25mb?

**Comment by nabilfreeman** [comment]
Alternately what about a timeout? It takes me approx 3 mins to upload to 40%...

**Comment by jackboberg** [comment]
The CLI timeout should be 5 minutes. We've been seeing an increase in reports of timeouts though, we are looking into it.

**Comment by jackboberg** [comment]
@nabilfreeman Can you retry using the new `meteor` image and an updated CLI:

`npm i modulus@next -g`

**Comment by JohnRodney** [comment]
@jackboberg I just tried the `npm i modulus@next -g` and then deploy again but it didn't fix the issue.  I'm having the same problem as the OP any other suggestions?

**Comment by JohnRodney** [comment]
I think this problem still exists or I'm following the steps wrong. 

I have a Meteor 1.3 project and I've tried versions `4.0.1, 5.0.1, 6.0.0`.

**Comment by harlanj** [comment]
@JohnRodney Is your project type set to Meteor?

**Comment by JohnRodney** [comment]
If you are talking about the runtime option in the GUI on the modulus site.  It currently is set to Meteor.

**Comment by harlanj** [comment]
@JohnRodney I took a look at your build logs and they don't look like it's using the right build image. Can you contact support so we can further look into this for you?

**Comment by JohnRodney** [comment]
@harlanj I can.  The only build that got through was the wrong image and not my particular issue.  

I think the timeout issue... which is mine is a separate issue.  Out of 12 uploads I've managed to only upload one time (so probably not in the server logs).  This may not even be meteor related, but this is the only thread that comes up from my exact error message.

<img width="363" alt="screen shot 2016-04-06 at 4 09 55 pm" src="https://cloud.githubusercontent.com/assets/11075982/14333018/0edf3cee-fc12-11e5-9f7b-34959fe9d45f.png">

**Comment by nabilfreeman** [comment]
@jackboberg this issue still happens after updated to the latest version of modulus and meteor.

The only way I'm able to deploy to Modulus right now is to spin up an EC2 box, install meteor, modulus, git, git pull and finally modulus deploy.

My connection is 16 down, 1 up which is a reasonable speed for everything else I do!

**Comment by foysalit** [comment]
Facing the same issue myself. I have approx. the same speed as @nabilfreeman. any hint how to get around this?

**Comment by nikhildaga** [comment]
Facing the same issue

**Comment by foysalit** [comment]
So we were using node.js runtime and modulus cli ***5.x***. Upgrading to cli ***6.x*** and changing the runtime to meteor.js seems to have brought down the project build to several megabytes and the deploy works just fine now. Kudos to the modulus team :+1:

**Comment by nikhildaga** [comment]
why is there a timeout for just 5 mins. It will fail for most people in India.
